#! /bin/sh

#
# Autostart
#

# Starting sxhkd which manages the keybindings
pgrep -x sxhkd > /dev/null || sxhkd &
source "$HOME/.config/bspwm/autostart.sh"

#
# bspwm config
#

# bspc monitor eDP-1 -d 'dev' 'doc' 'www' 'chat' 'mail' 'sys'
bspc monitor eDP-1 -d '1' '2' '3' '4' '5' '6'

bspc config border_width          2
bspc config window_gap            3
bspc config top_padding           35
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# reminder: you need to press the super key at the same time moving the mouse
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a firefox desktop='^3' follow=off focus=on
bspc rule -a discord desktop='^4' follow=off focus=on
bspc rule -a Emacs state=tiled focus=on follow=on manage=on

# Prevent bsp from stealing focus
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#9aedfe"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#282a36"
