theme = "rose_pine"

[editor]
line-number = "relative"
color-modes = true
cursorline = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "primary-selection-length",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "│"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "╎"
skip-levels = 0

[editor.lsp]
display-messages = true

[keys.insert]
C-c = "normal_mode"
"C-space" = "completion"

[keys.normal]
# Move around split windows
C-j = "jump_view_down"
C-k = "jump_view_up"
C-h = "jump_view_left"
C-l = "jump_view_right"

# Move lines up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# split line
C-J = ["insert_mode", "insert_newline", "normal_mode"]

[keys.normal.g]
q = ":bc"
Q = ":bc!"

[keys.select]
# Move lines up and down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
